# Generated by Django 4.1.3 on 2022-12-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_date_event_start_date_remove_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='store_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
