# Generated by Django 4.1.3 on 2022-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_options_rename_title_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('YEARLY', 'YEARLY')], default='DAILY', max_length=50, null=True),
        ),
    ]
