# Generated by Django 4.1.3 on 2022-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'NONE'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('YEARLY', 'YEARLY')], default='DAILY', max_length=50, null=True),
        ),
    ]
