# Generated by Django 4.1.3 on 2023-02-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'NONE'), ('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('YEARLY', 'YEARLY')], default='NONE', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='store_link',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
