# Generated by Django 4.1.3 on 2022-11-30 19:36

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='sub_text',
            new_name='sub_text_one',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='sub_text_two',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
