# Generated by Django 4.1.3 on 2022-12-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_landingpage_hero_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='whats_new_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
