# Generated by Django 4.1.3 on 2022-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_image_landingpage_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='banner_image',
            new_name='image',
        ),
    ]
