# Generated by Django 4.1.3 on 2022-11-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_delete_landingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='image',
            new_name='img',
        ),
    ]
