# Generated by Django 4.1.3 on 2022-11-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_image_homepage_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='img',
            new_name='image',
        ),
    ]
