# Generated by Django 4.1.3 on 2022-11-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_image_homepage_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='brand',
            new_name='nav_brand',
        ),
    ]
