# Generated by Django 4.1.3 on 2022-11-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_banner_image_homepage_banner_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='nav_brand',
        ),
    ]
