# Generated by Django 4.1.3 on 2022-12-15 18:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_header', wagtail.fields.RichTextField(blank=True)),
                ('location', wagtail.fields.RichTextField(blank=True)),
                ('hours', wagtail.fields.RichTextField(blank=True)),
                ('map_widget_url', models.URLField(blank=True, max_length=256)),
                ('about_header', wagtail.fields.RichTextField(blank=True)),
                ('about_text', wagtail.fields.RichTextField(blank=True)),
                ('about_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, 'wagtailcore.page'),
        ),
    ]
