# Generated by Django 4.1.3 on 2023-02-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='map_widget_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
