# Generated by Django 4.1.3 on 2023-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_map_widget_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='map_widget_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
