# Generated by Django 4.1.3 on 2022-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlespage',
            name='sub_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
