# Generated by Django 4.1.3 on 2022-12-06 15:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('singles', '0002_alter_singlespage_sub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlespage',
            name='sub_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
