# Generated by Django 4.1.3 on 2022-12-06 15:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('singles', '0003_alter_singlespage_sub_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlespage',
            old_name='logo',
            new_name='logo_1',
        ),
        migrations.RenameField(
            model_name='singlespage',
            old_name='sub_text',
            new_name='sub_text_one',
        ),
        migrations.AddField(
            model_name='singlespage',
            name='logo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='singlespage',
            name='logo_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='singlespage',
            name='sub_text_two',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
