# Generated by Django 4.1.3 on 2022-12-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_rename_nav_btn_navbar_nav_button_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='nav_image',
            new_name='logo',
        ),
    ]
