# Generated by Django 4.1.3 on 2022-12-02 17:01

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_link',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
