# Generated by Django 4.1.3 on 2022-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_banner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
