# Generated by Django 4.1.3 on 2022-12-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_newproducts_item_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproducts',
            old_name='item_1',
            new_name='item_1_stream',
        ),
    ]
