# Generated by Django 4.1.3 on 2022-12-05 15:21

from django.db import migrations
import products.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_item_1_newproducts_item_1_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='item_1_stream',
        ),
        migrations.AddField(
            model_name='newproducts',
            name='item_1',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.RichTextBlock(blank=True, features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'superscript', 'subscript', 'strikethrough', 'blockquote'], null=True, required=False)), ('image', products.models.ImageChooserBlock('item_1_image')), ('url', wagtail.blocks.URLBlock(help_text='Link to store page here (optional).', null=True, required=False))], blank=True, null=True, use_json_field=True),
        ),
    ]
