# Generated by Django 4.1.3 on 2022-12-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_newproducts_item_1_stream_newproducts_item_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproducts',
            old_name='item_1',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_1_img',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_1_text',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_2_img',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_2_text',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_3_img',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_3_text',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_4_img',
        ),
        migrations.RemoveField(
            model_name='newproducts',
            name='item_4_text',
        ),
    ]
