# Generated by Django 4.1.3 on 2022-12-05 15:59

from django.db import migrations
import products.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_item_1_newproducts_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproducts',
            old_name='product',
            new_name='product_1',
        ),
        migrations.AddField(
            model_name='newproducts',
            name='product_2',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.RichTextBlock(blank=True, features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'superscript', 'subscript', 'strikethrough', 'blockquote'], null=True, required=False)), ('image', products.models.ImageChooserBlock('item_2_image')), ('url', wagtail.blocks.URLBlock(help_text='Link to store page here (optional).', null=True, required=False))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='product_3',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.RichTextBlock(blank=True, features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'superscript', 'subscript', 'strikethrough', 'blockquote'], null=True, required=False)), ('image', products.models.ImageChooserBlock('item_3_image')), ('url', wagtail.blocks.URLBlock(help_text='Link to store page here (optional).', null=True, required=False))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='product_4',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.RichTextBlock(blank=True, features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'superscript', 'subscript', 'strikethrough', 'blockquote'], null=True, required=False)), ('image', products.models.ImageChooserBlock('item_4_image')), ('url', wagtail.blocks.URLBlock(help_text='Link to store page here (optional).', null=True, required=False))], blank=True, null=True, use_json_field=True),
        ),
    ]
