# Generated by Django 4.1.3 on 2022-12-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_newproducts_new_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproducts',
            old_name='new_product',
            new_name='new_products',
        ),
    ]
