# Generated by Django 4.1.3 on 2022-12-21 15:00

from django.db import migrations
import products.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_newproducts_new_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproducts',
            name='new_products',
            field=wagtail.fields.StreamField([('product', wagtail.blocks.StructBlock([('name', wagtail.blocks.RichTextBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(blank=True, features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'superscript', 'subscript', 'strikethrough', 'blockquote'], max_length=256, null=True, required=False)), ('image', products.models.ImageChooserBlock(blank=True, null=True, required=False)), ('link', wagtail.blocks.CharBlock(blank=True, null=False, required=False)), ('alt', wagtail.blocks.CharBlock(required=True))]))], blank=True, use_json_field=True),
        ),
    ]
